name: Train and Deploy on Ray Cluster

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs: 
    train-deploy:
        runs-on: ubuntu-latest
        env:
            ANYSCALE_CLI_TOKEN: ${{ secrets.ANYSCALE_CLI_TOKEN }}
            WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
            WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
            WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10.17'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Train on Ray Cluster
              run: |
                cd ray-train
                anyscale job submit --wait --working-dir . -- python submit_job.py